window.SERVICES = [
  ['Website Development','Turn more visits into enquiries with a fast, clear website built around your customers.',['Responsive, custom design','Fast loading and SEO-ready','Clear paths to contact','Easy to update']],
  ['Software and Web App Development','Make complex work simpler with software shaped around how your team works.',['Custom workflows','Secure, reliable foundations','Useful integrations','Room to grow']],
  ['Mobile App Development','Put a useful, polished experience in your customers’ hands.',['iOS and Android planning','Intuitive user journeys','Connected backend systems','Launch support']],
  ['SEO','Help the right people find you when they are ready to act.',['Technical site improvements','Search intent research','Useful content direction','Clear monthly reporting']],
  ['Google Ads','Reach high-intent customers and make every campaign easier to understand.',['Campaign and keyword setup','Conversion tracking','Ongoing optimisation','Transparent reporting']],
  ['Meta (Facebook and Instagram) Ads','Build demand with creative campaigns designed for the people you want to reach.',['Audience and offer planning','Ad creative direction','Campaign testing','Performance insights']],
  ['Social Media Marketing','Show up consistently with content that makes your brand memorable.',['Channel strategy','Content calendar','Post design and copy','Community guidance']],
  ['Digital Marketing (full funnel)','Connect discovery, consideration and conversion in one practical growth plan.',['Channel mix planning','Campaign execution','Lead journey improvements','Unified reporting']],
  ['WhatsApp API and Chatbot Automation','Reply faster and guide enquiries with helpful, human-feeling automation.',['WhatsApp API setup','Conversation flow design','Automated follow-ups','Team handover options']],
  ['Lead Generation and CRM Setup','Give your team a clear path from first enquiry to follow-up.',['Lead capture workflows','CRM setup and fields','Follow-up reminders','Pipeline visibility']],
  ['AI and Machine Learning Solutions','Put AI to work on a real business problem, with a clear path from idea to useful tool.',['Use-case discovery','Model and assistant development','Workflow integration','Practical handover']],
  ['Data Analysis and Business Insights','Turn scattered data into a sharper view of growth, costs and next steps.',['Data review and cleanup','Growth opportunity analysis','Cost-leakage investigation','Decision-ready reporting']],
  ['Personal Branding','Build a clear, credible presence around your expertise.',['Positioning and voice','Profile improvements','Content themes','Publishing direction']],
  ['Brand Identity and Graphic Design','Give your business a distinctive visual system people recognise.',['Visual direction','Logo and identity system','Brand colour and type','Reusable design assets']],
  ['UI/UX Design','Make digital products easier to understand, use and trust.',['User journey mapping','Wireframes and prototypes','Interface design','Usability improvements']],
  ['Content Writing and Copywriting','Explain your value clearly and help readers take the next step.',['Website and landing copy','Campaign messaging','Brand voice guidance','Search-aware writing']],
  ['Video Editing and Motion Graphics','Make your message move with considered edits and purposeful motion.',['Short and long-form edits','Motion graphics','Platform-ready exports','Consistent visual style']],
  ['Online Reputation Management','Build trust with a thoughtful approach to reviews and public feedback.',['Reputation review','Response guidance','Review request workflows','Ongoing monitoring plan']]
];
window.PROJECTS = [
  {title:'Machine Learning Models',category:'AI/ML',summary:'Models designed to help turn business questions into useful predictions.',problem:'Teams can have useful data but no clear way to apply it to everyday decisions.',solution:'We build and evaluate machine learning models around the question, available data and intended workflow.',tools:'Machine learning · Data preparation · Model evaluation',result:'Result details coming soon',link:'',image:'model'},
  {title:'AI Teaching Assistant',category:'AI/ML',summary:'An AI assistant concept to make learning support easier to access.',problem:'Learners need timely help while working through lessons and questions.',solution:'We develop AI teaching assistants and chatbots with clear knowledge boundaries and helpful conversation flows.',tools:'AI · Chatbots · Knowledge workflows',result:'Result details coming soon',link:'',image:'assistant'},
  {title:'Business Data Analysis and Cost-Leakage Insights',category:'Data',summary:'A practical view of growth opportunities, spend and marketing performance.',problem:'Business data can be spread across tools, making it hard to see where money goes and what works.',solution:'We analyse available business data to highlight growth potential, unwanted expenses and channels that bring customers.',tools:'Data analysis · Visualisation · Business insights',result:'Result details coming soon',link:'',image:'data'},
  {title:'My JEE Mentor',category:'Web',summary:'A learning platform for students preparing for engineering entrance exams.',problem:'Students need a focused, accessible online home for learning resources.',solution:'A website experience for My JEE Mentor, organised to help students find the support they need.',tools:'Web design · Web development',result:'Result details coming soon',link:'https://myjeementor-pi.vercel.app',image:'mentor'}
];
