(() => {
  const cfg=window.SITE_CONFIG,page=document.body.dataset.page;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const wa=(message)=>{const number=cfg.whatsappLink.match(/wa\.me\/(\d+)/)?.[1]||'';return `https://wa.me/${number}?text=${encodeURIComponent(message)}`;};
  const iconList=['◈','⌘','▣','⌕','↗','◉','✳','◌','☏','⌖','✧','▥','✦','◍','◇','✎','▷','◎'];
  const navLinks=[['Home','index.html','home'],['Services','services.html','services'],['Projects','projects.html','projects'],['Contact','contact.html','contact']];
  const header=document.getElementById('site-header');
  const brandMark=`<span class="brand-symbol">${esc(cfg.shortBrand.slice(0,3))}</span><span class="brand-word">${esc(cfg.shortBrand.slice(0,2))}<b>${esc(cfg.shortBrand.slice(2,3))}</b>${esc(cfg.shortBrand.slice(3))}</span>`;
  if(header){header.innerHTML=`<header class="site-header"><div class="nav-wrap"><a class="brand-lockup brand-image-link" href="index.html" aria-label="${esc(cfg.brand)} home"><img class="brand-image" src="logo.png" alt="${esc(cfg.brand)} logo"></a><nav class="nav-links" aria-label="Main navigation">${navLinks.map(([label,url,id])=>`<a href="${url}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav><a class="button button-primary nav-cta" data-whatsapp href="#">Free consultation <span>&#8599;</span></a><button class="theme-toggle" type="button" aria-label="Switch to day mode" aria-pressed="false" title="Switch to day mode"><svg class="theme-sun" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/></svg></button><button class="nav-toggle" aria-label="Open navigation" aria-expanded="false"><span></span></button></div></header>`;}
  const footer=document.getElementById('site-footer');
  if(footer){footer.innerHTML=`<footer class="site-footer"><div class="footer-main"><div class="footer-brand"><a class="brand-lockup" href="index.html">${brandMark}</a><p>${esc(cfg.tagline)}</p><a class="text-link" data-whatsapp href="#">Let’s talk <span>↗</span></a></div><div class="footer-col"><h4>EXPLORE</h4><a href="index.html">Home</a><a href="services.html">Services</a><a href="projects.html">Projects</a><a href="contact.html">Contact</a></div><div class="footer-col"><h4>WHAT WE DO</h4><a href="services.html">Digital experiences</a><a href="services.html#ai-data">AI & data</a><a href="services.html">Brand & growth</a><a href="careers.html">Careers</a></div><div class="footer-col"><h4>SAY HELLO</h4><a data-call href="#">${esc(cfg.phone)}</a><a data-email-link href="#">${esc(cfg.email)}</a><a data-whatsapp href="#">WhatsApp ↗</a></div></div><div class="footer-promise-strip"><span>First priority</span><i>&#183;</i><span>Support first</span><i>&#183;</i><span>Upgrades under one roof</span></div><div class="footer-bottom"><span>© <span data-year></span> ${esc(cfg.brand)}. Made with intention.</span><span>BUILT FOR WHAT’S NEXT&nbsp; ✳</span></div></footer>`;}
  const floating=document.getElementById('floating-actions');if(floating)floating.innerHTML='<div class="floating-actions"><a class="float-link whatsapp" data-whatsapp href="#" aria-label="Chat on WhatsApp"><span class="float-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12.04 2a9.96 9.96 0 0 0-8.52 15.12L2.2 22l5.02-1.3A9.96 9.96 0 1 0 12.04 2Z"/><path d="M8.15 7.25c-.22-.5-.46-.5-.67-.51h-.57c-.2 0-.52.08-.8.37-.28.3-1.05 1.03-1.05 2.5s1.08 2.9 1.23 3.1c.15.2 2.1 3.37 5.14 4.58.72.29 1.29.47 1.73.6.73.23 1.4.2 1.93.12.59-.09 1.82-.75 2.08-1.47.25-.72.25-1.34.18-1.47-.08-.13-.28-.2-.59-.36-.31-.15-1.82-.9-2.1-1-.28-.11-.49-.16-.69.15-.21.31-.8 1-1 1.2-.18.21-.36.24-.67.08-.31-.15-1.3-.48-2.48-1.54-.92-.82-1.54-1.84-1.72-2.15-.18-.31-.02-.48.14-.63.14-.14.31-.36.46-.54.15-.18.2-.31.31-.52.1-.2.05-.38-.03-.54-.08-.15-.69-1.64-.95-2.24Z"/></svg></span><span class="float-tip">Chat on WhatsApp</span></a><a class="float-link call" data-call href="#" aria-label="Call us"><span class="float-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7.2 3.5 9.6 3c.7-.1 1.3.3 1.5 1l1 3.1c.2.6 0 1.2-.5 1.6l-1.5 1.2a14.5 14.5 0 0 0 4.1 4.1l1.2-1.5c.4-.5 1-.7 1.6-.5l3.1 1c.7.2 1.1.8 1 1.5l-.5 2.4c-.2.9-1 1.6-2 1.6A15.8 15.8 0 0 1 4.6 5.5c0-1 .7-1.8 1.6-2Z"/></svg></span><span class="float-tip">Call the team</span></a></div>'
  document.querySelectorAll('[data-whatsapp]').forEach(a=>{a.href=cfg.whatsappLink;a.target='_blank';a.rel='noopener noreferrer';});
  document.querySelectorAll('[data-call]').forEach(a=>a.href=cfg.callLink);
  document.querySelectorAll('[data-phone]').forEach(el=>el.textContent=cfg.phone);
  document.querySelectorAll('[data-email]').forEach(el=>el.textContent=cfg.email);
  document.querySelectorAll('[data-email-link]').forEach(a=>a.href=`mailto:${cfg.email}`);
  document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
  const themeButton=document.querySelector('.theme-toggle');
  const themeIcon=(mode)=>mode==='light'?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.2 15.4A8.5 8.5 0 0 1 8.6 3.8 8.5 8.5 0 1 0 20.2 15.4Z"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/></svg>';
  const setTheme=(mode,save=false)=>{const light=mode==='light';if(light)document.documentElement.dataset.theme='light';else delete document.documentElement.dataset.theme;themeButton?.setAttribute('aria-pressed',String(light));themeButton?.setAttribute('aria-label',`Switch to ${light?'night':'day'} mode`);themeButton?.setAttribute('title',`Switch to ${light?'night':'day'} mode`);if(themeButton)themeButton.innerHTML=themeIcon(mode);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',light?'#f3f5fb':'#080a18');if(save){try{localStorage.setItem('dk-theme',mode);}catch{}}};
  setTheme(document.documentElement.dataset.theme==='light'?'light':'dark');themeButton?.addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='light'?'dark':'light'));
  const toggle=document.querySelector('.nav-toggle'),siteHeader=document.querySelector('.site-header');
  toggle?.addEventListener('click',()=>{const open=siteHeader.classList.toggle('nav-open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
  document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{siteHeader?.classList.remove('nav-open');toggle?.setAttribute('aria-expanded','false');}));
  let prevY=window.scrollY,scrollQueued=false;window.addEventListener('scroll',()=>{if(scrollQueued)return;scrollQueued=true;requestAnimationFrame(()=>{const y=window.scrollY;siteHeader?.classList.toggle('scrolled',y>12);if(y<100)siteHeader?.classList.remove('header-hidden');else if(y>prevY+5)siteHeader?.classList.add('header-hidden');else if(y<prevY-5)siteHeader?.classList.remove('header-hidden');prevY=y;const max=document.documentElement.scrollHeight-innerHeight;const progress=document.querySelector('.scroll-progress');if(progress)progress.style.width=`${max>0?Math.min(100,y/max*100):0}%`;scrollQueued=false;});},{passive:true});
  const serviceCard=(s,i,detail=false)=>{const [title,pitch,benefits]=s;const msg=`Hi ${cfg.shortBrand}, I’d like to know more about ${title}.`;return `<article class="service-card reveal ${i===0?'featured':''}" data-tilt><div class="card-meta"><span>SERVICE / ${String(i+1).padStart(2,'0')}</span><i>${iconList[i%iconList.length]}</i></div><div class="service-icon">${iconList[i%iconList.length]}</div><h3>${esc(title)}</h3><p>${esc(pitch)}</p>${detail?`<ul class="benefit-list">${benefits.map(b=>`<li>${esc(b)}</li>`).join('')}</ul><a class="service-cta" href="${wa(msg)}" target="_blank" rel="noopener noreferrer">Ask about this service <span>↗</span></a>`:`<a class="card-arrow" href="services.html">Explore service&nbsp; ↗</a>`}</article>`;};
  const homeServices=document.getElementById('home-services');if(homeServices){const picks=[0,1,2,3,8,10,11,13];homeServices.innerHTML=picks.map(i=>serviceCard(SERVICES[i],i)).join('');homeServices.querySelectorAll('.reveal').forEach(el=>el.classList.add('is-visible'));}
  const allServices=document.getElementById('all-services');if(allServices){allServices.innerHTML=SERVICES.map((s,i)=>serviceCard(s,i,true)).join('');allServices.querySelectorAll('.reveal').forEach(el=>el.classList.add('is-visible'));}
  const featured=document.getElementById('featured-projects');if(featured){featured.innerHTML=PROJECTS.slice(0,3).map(p=>`<a class="featured-project reveal is-visible" href="projects.html"><div class="project-art ${esc(p.image)}"><span class="art-label">${esc(p.category)} / SELECTED WORK</span></div><div class="featured-copy"><span>${esc(p.category.toUpperCase())} · EXPLORE PROJECT</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p></div></a>`).join('');}
  const projectGrid=document.getElementById('project-grid'),filterHost=document.getElementById('project-filters');
  if(projectGrid&&filterHost){const filters=['All','AI/ML','Web','Apps','Marketing','Data'];filterHost.innerHTML=filters.map((f,i)=>`<button class="filter-button ${i===0?'active':''}" data-filter="${esc(f)}" aria-pressed="${i===0}">${esc(f)}</button>`).join('');const render=items=>{projectGrid.innerHTML=items.map((p,i)=>`<article class="project-card reveal is-visible" tabindex="0" role="button" data-project="${PROJECTS.indexOf(p)}" aria-label="View ${esc(p.title)} project details"><div class="project-art ${esc(p.image)}"><span class="art-label">${esc(p.category.toUpperCase())} / ${esc(cfg.shortBrand.toUpperCase())}</span></div><div class="project-card-body"><div class="project-card-meta"><span>${esc(p.category.toUpperCase())}</span><span>0${i+1} / ${String(items.length).padStart(2,'0')}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><span class="text-link">View project <span>↗</span></span></div></article>`).join('');projectGrid.querySelectorAll('.project-card').forEach(el=>{el.addEventListener('click',()=>showProject(+el.dataset.project));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showProject(+el.dataset.project);}});});};render(PROJECTS);filterHost.addEventListener('click',e=>{const btn=e.target.closest('[data-filter]');if(!btn)return;filterHost.querySelectorAll('.filter-button').forEach(b=>{const active=b===btn;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});render(btn.dataset.filter==='All'?PROJECTS:PROJECTS.filter(p=>p.category===btn.dataset.filter));});}
  const modal=document.getElementById('project-modal'),modalContent=document.getElementById('modal-content');let lastFocus;
  function showProject(index){const p=PROJECTS[index];if(!p||!modal)return;lastFocus=document.activeElement;modalContent.innerHTML=`<p class="eyebrow">${esc(p.category)} / SELECTED WORK</p><h2 id="modal-title">${esc(p.title)}</h2><p>${esc(p.summary)}</p><div class="modal-field"><h3>THE PROBLEM</h3><p>${esc(p.problem)}</p></div><div class="modal-field"><h3>WHAT WE DID</h3><p>${esc(p.solution)}</p></div><div class="modal-field"><h3>TOOLS & APPROACH</h3><p>${esc(p.tools)}</p></div><div class="modal-field"><h3>RESULT</h3><p>${esc(p.result)}</p></div>${p.link?`<a class="button button-primary" href="${esc(p.link)}" target="_blank" rel="noopener noreferrer">Visit project <span>↗</span></a>`:''}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';modal.querySelector('.modal-close').focus();}
  function closeModal(){if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';lastFocus?.focus();}
  modal?.querySelectorAll('[data-close-modal]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
  const form=document.getElementById('contact-form');if(form){const select=form.elements.service;SERVICES.forEach(([title])=>{const o=document.createElement('option');o.value=title;o.textContent=title;select.append(o);});form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d=new FormData(form),message=`Hi ${cfg.shortBrand}, I’m ${d.get('name')}.\nPhone: ${d.get('phone')}\nService: ${d.get('service')}\nProject details: ${d.get('message')||'I’d like to discuss this with your team.'}`;window.open(wa(message),'_blank','noopener,noreferrer');});}
  document.querySelectorAll('[data-careers-whatsapp]').forEach(a=>a.href=wa(`Hi ${cfg.shortBrand}, I'd love to introduce myself for a career opportunity. I'm interested in sharing my experience and portfolio.`));
})();
